repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
    -   id: end-of-file-fixer
    -   id: check-toml
    -   id: check-added-large-files
        args: ['--maxkb=1024']
    -   id: check-case-conflict
    -   id: mixed-line-ending
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.9.0
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.2
    hooks:
    -   id: autopep8
-   repo: https://github.com/PyCQA/flake8
    rev: "6.0.0"
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-comprehensions
          - flake8-bugbear
          - flake8-polyfill
          - toml
        exclude: docs\/.*
