"""Init

Revision ID: c9e0a62f61ff
Revises: 
Create Date: 2023-04-02 01:35:50.810223

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "c9e0a62f61ff"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cthulhu_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("fs_uniquifier", sa.String(length=255), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_ip", sa.String(length=64), nullable=True),
        sa.Column("current_login_ip", sa.String(length=64), nullable=True),
        sa.Column("login_count", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cthulhu_user")),
        sa.UniqueConstraint(
            "fs_uniquifier", name=op.f("uq_cthulhu_user_fs_uniquifier")
        ),
        sa.UniqueConstraint("username", name=op.f("uq_cthulhu_user_username")),
    )
    op.create_table(
        "limelight_product",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("allergen", sa.String(length=64), nullable=True),
        sa.Column("organic", sa.Boolean(), nullable=True),
        sa.Column("vegan", sa.Boolean(), nullable=True),
        sa.Column("type", sa.String(length=64), nullable=True),
        sa.Column("brand", sa.String(length=64), nullable=True),
        sa.Column("weight", sa.Integer(), nullable=True),
        sa.Column("volume", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_limelight_product")),
    )
    op.create_table(
        "limelight_recipe",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("time", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_limelight_recipe")),
    )
    op.create_table(
        "security_role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=True),
        sa.Column("description", mysql.LONGTEXT(), nullable=True),
        sa.Column("permissions", mysql.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_security_role")),
        sa.UniqueConstraint("name", name=op.f("uq_security_role_name")),
    )
    op.create_table(
        "limelight_ingredient",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("recipe_id", sa.Integer(), nullable=True),
        sa.Column("quantity", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["limelight_product.id"],
            name=op.f("fk_limelight_ingredient_product_id_limelight_product"),
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["limelight_recipe.id"],
            name=op.f("fk_limelight_ingredient_recipe_id_limelight_recipe"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_limelight_ingredient")),
    )
    op.create_table(
        "security_roles_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["security_role.id"],
            name=op.f("fk_security_roles_users_role_id_security_role"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["cthulhu_user.id"],
            name=op.f("fk_security_roles_users_user_id_cthulhu_user"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_security_roles_users")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("security_roles_users")
    op.drop_table("limelight_ingredient")
    op.drop_table("security_role")
    op.drop_table("limelight_recipe")
    op.drop_table("limelight_product")
    op.drop_table("cthulhu_user")
    # ### end Alembic commands ###
