"""project data

Revision ID: 057cdc26733c
Revises: 08945bf93402
Create Date: 2024-12-30 00:07:51.213928

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "057cdc26733c"
down_revision = "08945bf93402"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("limelight_project", schema=None) as batch_op:
        batch_op.add_column(sa.Column("current_release", sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column("issues_open", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("issues_closed", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("stars", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("forks", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("network", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("watchers", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("subscribers", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("downloads", sa.Integer(), nullable=True))

    with op.batch_alter_table("limelight_project_stats", schema=None) as batch_op:
        batch_op.add_column(sa.Column("downloads", sa.Integer(), nullable=True))
        batch_op.drop_column("downloads_w")
        batch_op.drop_column("downloads_d")
        batch_op.drop_column("downloads_m")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("limelight_project_stats", schema=None) as batch_op:
        batch_op.add_column(sa.Column("downloads_m", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("downloads_d", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("downloads_w", sa.INTEGER(), nullable=True))
        batch_op.drop_column("downloads")

    with op.batch_alter_table("limelight_project", schema=None) as batch_op:
        batch_op.drop_column("downloads")
        batch_op.drop_column("subscribers")
        batch_op.drop_column("watchers")
        batch_op.drop_column("network")
        batch_op.drop_column("forks")
        batch_op.drop_column("stars")
        batch_op.drop_column("issues_closed")
        batch_op.drop_column("issues_open")
        batch_op.drop_column("current_release")

    # ### end Alembic commands ###
