"""tag icon

Revision ID: 08945bf93402
Revises: 5e2a97392513
Create Date: 2024-12-29 01:47:32.793967

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "08945bf93402"
down_revision = "5e2a97392513"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("limelight_tag", schema=None) as batch_op:
        batch_op.add_column(sa.Column("icon", sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("limelight_tag", schema=None) as batch_op:
        batch_op.drop_column("icon")

    # ### end Alembic commands ###
