"""GithubRepo.licence to json

Revision ID: 0a06d2b259b4
Revises: f1fb6812161b
Create Date: 2023-07-31 22:12:12.797811

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "0a06d2b259b4"
down_revision = "f1fb6812161b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("limelight_repo_github", schema=None) as batch_op:
        batch_op.alter_column(
            "license", existing_type=mysql.VARCHAR(length=32), type_=sa.JSON(), existing_nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("limelight_repo_github", schema=None) as batch_op:
        batch_op.alter_column(
            "license", existing_type=sa.JSON(), type_=mysql.VARCHAR(length=32), existing_nullable=True
        )

    # ### end Alembic commands ###
