"""GithubRepo->StarQueue

Revision ID: 13cf293a1c9c
Revises: d201d91725ca
Create Date: 2023-07-30 23:54:28.221697

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "13cf293a1c9c"
down_revision = "d201d91725ca"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("limelight_repo_github", schema=None) as batch_op:
        batch_op.add_column(sa.Column("github_json_url", sa.String(length=128), nullable=True))

    with op.batch_alter_table("limelight_star_queue", schema=None) as batch_op:
        batch_op.add_column(sa.Column("github_repo_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_limelight_star_queue_github_repo_id_limelight_repo_github"),
            "limelight_repo_github",
            ["github_repo_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("limelight_star_queue", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_limelight_star_queue_github_repo_id_limelight_repo_github"), type_="foreignkey"
        )
        batch_op.drop_column("github_repo_id")

    with op.batch_alter_table("limelight_repo_github", schema=None) as batch_op:
        batch_op.drop_column("github_json_url")

    # ### end Alembic commands ###
