"""project info

Revision ID: 5e2a97392513
Revises: e273c4f2048c
Create Date: 2024-12-28 22:22:50.167807

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5e2a97392513"
down_revision = "e273c4f2048c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("limelight_project", schema=None) as batch_op:
        batch_op.add_column(sa.Column("readme_type", sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column("creation_date", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("last_release_date", sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_column("readme_ext")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("limelight_project", schema=None) as batch_op:
        batch_op.add_column(sa.Column("readme_ext", sa.VARCHAR(length=3), nullable=True))
        batch_op.drop_column("last_release_date")
        batch_op.drop_column("creation_date")
        batch_op.drop_column("readme_type")

    # ### end Alembic commands ###
