"""data

Revision ID: 6830a05fe368
Revises: de655c9233ba
Create Date: 2025-01-25 02:05:33.420206

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = "6830a05fe368"
down_revision = "de655c9233ba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("limelight_project", schema=None) as batch_op:
        batch_op.alter_column(
            "supported_python", existing_type=sqlite.JSON(), type_=sa.String(length=128), existing_nullable=True
        )
        batch_op.alter_column(
            "supported_flask", existing_type=sa.VARCHAR(length=32), type_=sa.String(length=128), existing_nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("limelight_project", schema=None) as batch_op:
        batch_op.alter_column(
            "supported_flask", existing_type=sa.String(length=128), type_=sa.VARCHAR(length=32), existing_nullable=True
        )
        batch_op.alter_column(
            "supported_python", existing_type=sa.String(length=128), type_=sqlite.JSON(), existing_nullable=True
        )

    # ### end Alembic commands ###
