"""GithubRepo.dates

Revision ID: 786857c65bbb
Revises: cc32fb56da4a
Create Date: 2023-07-31 19:41:58.220381

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "786857c65bbb"
down_revision = "cc32fb56da4a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("limelight_repo_github", schema=None) as batch_op:
        batch_op.alter_column("creation_date", existing_type=mysql.DATETIME(), nullable=True)
        batch_op.alter_column("last_push_date", existing_type=mysql.DATETIME(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("limelight_repo_github", schema=None) as batch_op:
        batch_op.alter_column("last_push_date", existing_type=mysql.DATETIME(), nullable=False)
        batch_op.alter_column("creation_date", existing_type=mysql.DATETIME(), nullable=False)

    # ### end Alembic commands ###
