"""project data

Revision ID: a1a704c10a03
Revises: 057cdc26733c
Create Date: 2024-12-30 00:25:35.597695

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a1a704c10a03"
down_revision = "057cdc26733c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("limelight_project", schema=None) as batch_op:
        batch_op.add_column(sa.Column("supported_flask", sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column("last_release", sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column("first_release_date", sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_column("current_release")
        batch_op.drop_column("creation_date")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("limelight_project", schema=None) as batch_op:
        batch_op.add_column(sa.Column("creation_date", sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column("current_release", sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_column("first_release_date")
        batch_op.drop_column("last_release")
        batch_op.drop_column("supported_flask")

    # ### end Alembic commands ###
