"""data

Revision ID: b67b134260af
Revises: a893251b8be0
Create Date: 2025-01-22 00:50:23.440131

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b67b134260af"
down_revision = "a893251b8be0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "limelight_project_queue",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("processed", sa.Boolean(), nullable=False),
        sa.Column("origin", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "modified_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["limelight_project.id"],
            name=op.f("fk_limelight_project_queue_project_id_limelight_project"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_limelight_project_queue")),
    )
    with op.batch_alter_table("limelight_project", schema=None) as batch_op:
        batch_op.add_column(sa.Column("downloads_data", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("downloads_data_date", sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("limelight_project", schema=None) as batch_op:
        batch_op.drop_column("downloads_data_date")
        batch_op.drop_column("downloads_data")

    op.drop_table("limelight_project_queue")
    # ### end Alembic commands ###
