"""GithubRepo.namespace

Revision ID: cc32fb56da4a
Revises: e7527d942727
Create Date: 2023-07-31 19:35:38.197222

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cc32fb56da4a"
down_revision = "e7527d942727"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("limelight_repo_github", schema=None) as batch_op:
        batch_op.add_column(sa.Column("namespace", sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("limelight_repo_github", schema=None) as batch_op:
        batch_op.drop_column("namespace")

    # ### end Alembic commands ###
