"""Github Repo

Revision ID: d201d91725ca
Revises: dd4730f795ff
Create Date: 2023-07-30 23:06:30.254226

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d201d91725ca"
down_revision = "dd4730f795ff"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("limelight_star", schema=None) as batch_op:
        batch_op.add_column(sa.Column("github_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_limelight_star_github_id_limelight_repo_github"),
            "limelight_repo_github",
            ["github_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("limelight_star", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_limelight_star_github_id_limelight_repo_github"), type_="foreignkey")
        batch_op.drop_column("github_id")

    # ### end Alembic commands ###
