"""Project Stats

Revision ID: dbf7334c7184
Revises: fcdd25bd325c
Create Date: 2024-12-28 01:24:53.056917

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "dbf7334c7184"
down_revision = "fcdd25bd325c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "limelight_project_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("date_creation", sa.DateTime(timezone=True), nullable=True),
        sa.Column("date_modification", sa.DateTime(timezone=True), nullable=True),
        sa.Column("date_pushed", sa.DateTime(timezone=True), nullable=True),
        sa.Column("issues_open", sa.Integer(), nullable=False),
        sa.Column("issues_closed", sa.Integer(), nullable=False),
        sa.Column("stars", sa.Integer(), nullable=False),
        sa.Column("forks", sa.Integer(), nullable=False),
        sa.Column("network", sa.Integer(), nullable=False),
        sa.Column("watchers", sa.Integer(), nullable=False),
        sa.Column("subscribers", sa.Integer(), nullable=False),
        sa.Column("downloads_d", sa.Integer(), nullable=False),
        sa.Column("downloads_w", sa.Integer(), nullable=False),
        sa.Column("downloads_m", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "modified_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_limelight_project_stats")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("limelight_project_stats")
    # ### end Alembic commands ###
