"""data

Revision ID: de655c9233ba
Revises: b67b134260af
Create Date: 2025-01-22 23:59:22.560567

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "de655c9233ba"
down_revision = "b67b134260af"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("limelight_project_queue", schema=None) as batch_op:
        batch_op.add_column(sa.Column("data", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("limelight_project_queue", schema=None) as batch_op:
        batch_op.drop_column("data")

    # ### end Alembic commands ###
