"""project info

Revision ID: e273c4f2048c
Revises: ef0d895be806
Create Date: 2024-12-28 22:19:04.827883

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e273c4f2048c"
down_revision = "ef0d895be806"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("limelight_project", schema=None) as batch_op:
        batch_op.add_column(sa.Column("readme", sa.String(length=16000), nullable=True))
        batch_op.add_column(sa.Column("readme_ext", sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column("license", sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("limelight_project", schema=None) as batch_op:
        batch_op.drop_column("license")
        batch_op.drop_column("readme_ext")
        batch_op.drop_column("readme")

    # ### end Alembic commands ###
