"""Project Stats relationship

Revision ID: e619ebcf0856
Revises: 4e80614ce15c
Create Date: 2024-12-28 01:34:14.948435

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e619ebcf0856"
down_revision = "4e80614ce15c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("limelight_project_stats", schema=None) as batch_op:
        batch_op.add_column(sa.Column("project_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            batch_op.f("fk_limelight_project_stats_project_id_limelight_project"),
            "limelight_project",
            ["project_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("limelight_project_stats", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_limelight_project_stats_project_id_limelight_project"), type_="foreignkey"
        )
        batch_op.drop_column("project_id")

    # ### end Alembic commands ###
