"""GithubRepo Structure

Revision ID: e7527d942727
Revises: 13cf293a1c9c
Create Date: 2023-07-31 00:13:27.962393

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e7527d942727"
down_revision = "13cf293a1c9c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("limelight_repo_github", schema=None) as batch_op:
        batch_op.add_column(sa.Column("name", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("full_name", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("html_url", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("description", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("license", sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column("default_branch", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("fork", sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column("template", sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column("archived", sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column("creation_date", sa.DateTime(timezone=True), nullable=False))
        batch_op.add_column(sa.Column("last_push_date", sa.DateTime(timezone=True), nullable=False))
        batch_op.add_column(sa.Column("stargazers_count", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("watchers_count", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("forks_count", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("open_issues_count", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("network_count", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("subscribers_count", sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("limelight_repo_github", schema=None) as batch_op:
        batch_op.drop_column("subscribers_count")
        batch_op.drop_column("network_count")
        batch_op.drop_column("open_issues_count")
        batch_op.drop_column("forks_count")
        batch_op.drop_column("watchers_count")
        batch_op.drop_column("stargazers_count")
        batch_op.drop_column("last_push_date")
        batch_op.drop_column("creation_date")
        batch_op.drop_column("archived")
        batch_op.drop_column("template")
        batch_op.drop_column("fork")
        batch_op.drop_column("default_branch")
        batch_op.drop_column("license")
        batch_op.drop_column("description")
        batch_op.drop_column("html_url")
        batch_op.drop_column("full_name")
        batch_op.drop_column("name")

    # ### end Alembic commands ###
