"""GithubRepo.dates to strings

Revision ID: f1fb6812161b
Revises: 786857c65bbb
Create Date: 2023-07-31 21:24:40.282703

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "f1fb6812161b"
down_revision = "786857c65bbb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("limelight_repo_github", schema=None) as batch_op:
        batch_op.alter_column(
            "creation_date", existing_type=mysql.DATETIME(), type_=sa.String(length=32), existing_nullable=True
        )
        batch_op.alter_column(
            "last_push_date", existing_type=mysql.DATETIME(), type_=sa.String(length=32), existing_nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("limelight_repo_github", schema=None) as batch_op:
        batch_op.alter_column(
            "last_push_date", existing_type=sa.String(length=32), type_=mysql.DATETIME(), existing_nullable=True
        )
        batch_op.alter_column(
            "creation_date", existing_type=sa.String(length=32), type_=mysql.DATETIME(), existing_nullable=True
        )

    # ### end Alembic commands ###
